import { chmodSync, writeFileSync } from "node:fs";
import type { Config } from "./config.js";

const RUNTIME_ENV_KEYS = [
  "QQ_APP_ID",
  "QQ_APP_SECRET",
  "QQ_API_BASE",
  "HTTP_PROXY",
  "HTTPS_PROXY",
  "ALL_PROXY",
  "NO_PROXY",
  "http_proxy",
  "https_proxy",
  "all_proxy",
  "no_proxy",
  "DATA_DIR",
  "CODEX_HOME",
  "WORKSPACE_DIR"
];

export function writeRuntimeEnvFile(config: Config): void {
  const lines: string[] = [
    "# Generated by codex-qqbot. Contains secrets. Do not commit.",
    `DATA_DIR=${shellQuote(config.dataDir)}`,
    `CODEX_HOME=${shellQuote(config.codexHome ?? process.env.CODEX_HOME ?? "/codex-home")}`,
    `WORKSPACE_DIR=${shellQuote(config.workspaceDir)}`
  ];

  for (const key of RUNTIME_ENV_KEYS) {
    const value = process.env[key];
    if (!value) continue;
    if (key === "DATA_DIR" || key === "CODEX_HOME" || key === "WORKSPACE_DIR") continue;
    lines.push(`${key}=${shellQuote(value)}`);
  }

  writeFileSync(config.runtimeEnvFile, `${lines.join("\n")}\n`, { mode: 0o600 });
  chmodSync(config.runtimeEnvFile, 0o600);
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
